# Generated by Django 6.0.2 on 2026-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('board', models.CharField(choices=[('cbse', 'cbse'), ('stAte board', 'state board'), ('icse', 'icse')], max_length=20)),
                ('stablished_year', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='media/img/school_logo')),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
