# Generated by Django 6.0.2 on 2026-05-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='discription',
            new_name='description',
        ),
    ]
