# Generated by Django 6.0.2 on 2026-05-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_discription_school_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/school_logo/'),
        ),
    ]
