# Generated by Django 6.0.2 on 2026-05-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.URLField(default='Address not provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
