# Generated by Django 6.0.2 on 2026-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_school_address_school_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/school_logo/'),
        ),
    ]
