# Generated by Django 6.0.2 on 2026-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_address_alter_school_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')])),
                ('total_sets', models.PositiveIntegerField()),
                ('avilable_sets', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parent_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=50)),
                ('child_name', models.CharField(max_length=50)),
                ('phone_no', models.PositiveIntegerField()),
                ('E_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('collage_name', models.CharField(max_length=80)),
                ('teaching_exprience', models.PositiveIntegerField()),
                ('core_subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='affiliation_number',
            field=models.PositiveIntegerField(default=1231),
        ),
        migrations.AddField(
            model_name='school',
            name='recognition_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='img/recognition_certificate/'),
        ),
        migrations.AddField(
            model_name='school',
            name='udise_code',
            field=models.PositiveIntegerField(default=123456789),
        ),
    ]
