# Generated by Django 6.0.2 on 2026-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_classes_parent_info_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent_info',
            old_name='child_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='parent_info',
            name='pasward',
            field=models.PositiveIntegerField(default=1234),
        ),
    ]
