# Generated by Django 6.0.2 on 2026-06-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_child_name_parent_info_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent_info',
            old_name='last_name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='parent_info',
            name='resister',
            field=models.DateField(auto_now=True),
        ),
    ]
