# Generated by Django 6.0.2 on 2026-06-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_last_name_parent_info_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='parent_info',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/parent_covers/'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('class_grade', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='school.parent_info')),
            ],
        ),
    ]
